# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-service-account
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-sa-rolebinding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-service-account
    namespace: argocd
roleRef:
  kind: Role
  name: admin  # or use a custom role that grants necessary permissions
  apiGroup: rbac.authorization.k8s.io